<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1550698063504" stop="1550698063504">
  <description>This is the tests collection phase. Failures are modules that failed to collect.</description>
  <name>test_collection_phase</name>
  <title>Collection phase</title>
  <labels/>
  <test-cases>
    <test-case start="1550698063504" status="broken" stop="1550698063504">
      <name>test_del_group</name>
      <failure>
        <message>failed</message>
        <stack-trace>c:\users\serbin\appdata\local\programs\python\python37-32\lib\site-packages\_pytest\python.py:450: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
c:\users\serbin\appdata\local\programs\python\python37-32\lib\site-packages\py\_path\local.py:668: in pyimport
    __import__(modname)
E     File "f:\workspace\tests\python_training\test\test_del_group.py", line 25
E       old_groups.remove(group)
E       ^
E   IndentationError: unexpected indent</stack-trace>
      </failure>
      <attachments/>
      <labels/>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
